title: Welcome to Edie Park's Homepage
logo: /assets/img/retriever.jpg
description: ""
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Add navigation links here:
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Research"
    url: "/research"
  - title: "Piano"
    url: "/piano"
  - title: "School"
    url: "/school"
  - title: "Outreach"
    url: "/outreach"
  
include:
  - mydocs